name: build

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      #      - name: Build with Gradle
      #        run: >
      #          ./gradlew --no-configuration-cache
      #          :browserApp:wasmJsBrowserDistribution
      #          :androidApp:assembleDebug
      #          :desktopApp:package

      - name: Checkout website
        uses: actions/checkout@v6
        with:
          repository: BoD/bod.github.io
          path: 'website'
          token: ${{ github.token }}

      - name: Copy distribution to website
        run: |
          #          rm -rf website/linez0rz9000
          #          mkdir -p website/linez0rz9000
          #          cp -r browserApp/build/dist/wasmJs/productionExecutable/ website/linez0rz9000
               date > website/linez0rz9000/build_time.txt

      - name: Commit and push changes to website
        run: |
          cd website
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add linez0rz9000
          git commit -m "Update linez0rz9000" || echo "No changes to commit"
          git push origin master


#      - name: Archive distribution
#        uses: actions/upload-artifact@v5
#        with:
#          path: build/prodDist
#          name: prodDist
